/* DO NOT EDIT THIS FILE - it is machine generated */
#include "/home/maoguidong/.jdks/openjdk-14.0.2/include/jni.h"
/* Header for class mao_gui_dong_jni_MyJniTest */

#ifndef _Included_mao_gui_dong_jni_MyJniTest
#define _Included_mao_gui_dong_jni_MyJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mao_gui_dong_jni_MyJniTest
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mao_gui_dong_jni_MyJniTest_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
